namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingCoreLionDynasty : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',0,3,NULL,0,0,0,'obstinate-recruit','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_67.jpg',0,0,'false','false',2,NULL,'Obstinate Recruit',0,NULL,NULL,'dynasty',0,NULL,'If an opponent is more honorable than you, discard this character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',1,3,NULL,0,1,0,'ikoma-prodigy','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_68.jpg',0,0,'false','false',0,NULL,'Ikoma Prodigy',2,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After 1 or more fate is placed on this character – gain 1 honor.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',1,3,NULL,0,1,0,'matsu-berserker','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_69.jpg',0,0,'false','false',3,NULL,'Matsu Berserker',0,NULL,NULL,'dynasty',0,NULL,NULL,'character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',1,3,NULL,0,1,0,'steadfast-samurai','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_70.jpg',0,0,'false','false',1,NULL,'Steadfast Samurai',1,NULL,NULL,'dynasty',0,NULL,'<b>Forced Reaction:</b> After the fate phase begins, if you have at least 5 more honor than an opponent – this character cannot be discarded or lose fate this phase.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',2,3,NULL,0,2,0,'akodo-gunso','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_71.jpg',0,0,'false','false',2,NULL,'Akodo Gunsō',1,NULL,NULL,'dynasty',0,NULL,'Pride. <i>(After this character wins a conflict, honor it. After this character loses a conflict, dishonor it.)</i> <b>Reaction:</b> After this character enters play from a province – refill that province faceup.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',2,3,NULL,0,0,0,'deathseeker','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_72.jpg',0,0,'false','false',2,NULL,'Deathseeker',1,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After this character loses a conflict as an attacker, sacrifice this character. Choose a character controlled by your opponent – if that character has no fate on it, discard it. Otherwise, remove 1 fate from that character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',2,3,NULL,0,3,0,'venerable-historian','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_73.jpg',0,0,'false','false',0,NULL,'Venerable Historian',1,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is participating in a conflict, if you are more honorable than your opponent – honor this character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',3,3,NULL,0,2,0,'kitsu-spiritcaller','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_74.jpg',0,0,'false','false',1,NULL,'Kitsu Spiritcaller',3,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> During a conflict, bow this character. Choose a character in one of your discard piles – put that character into play in the conflict. If that character is still in play at the end of the conflict, return it to the bottom of its deck.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',3,3,NULL,0,1,0,'lion-s-pride-brawler','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_75.jpg',0,0,'false','false',3,NULL,'Lion''s Pride Brawler',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is attacking, choose a character with equal or lower [conflict-military] skill than this character – bow that character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',3,3,NULL,0,2,0,'matsu-beiona','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_76.jpg',0,0,'false','false',3,NULL,'Matsu Beiona',2,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After this character enters play, if you control 3 or more other <em>Bushi</em> characters – place 2 fate on this character.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',4,3,NULL,0,2,0,'honored-general','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_77.jpg',0,0,'false','false',3,NULL,'Honored General',1,NULL,NULL,'dynasty',0,NULL,'During a conflict in which this character is participating, each other participating [clan-lion] character you control gets +1[conflict-military]. <b>Reaction:</b> After this character enters play – honor it.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',4,3,NULL,0,3,0,'ikoma-eiji','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_78.jpg',0,0,'false','false',1,NULL,'Ikoma Eiji',3,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After you lose a [conflict-political] conflict – put a <em>Bushi</em> character with printed cost 3 or lower into play from your dynasty discard pile or provinces.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',5,3,NULL,0,3,0,'akodo-toturi','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_79.jpg',0,0,'false','false',6,NULL,'Akodo Toturi',3,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After you claim a ring during a [conflict-military] conflict in which this character is participating – resolve that ring''s effect.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('lion',0,3,NULL,0,0,0,'staging-ground','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_80.jpg',0,0,'false','false',0,NULL,'Staging Ground',0,NULL,NULL,'dynasty',0,+1,'<b>Action:</b> Choose up to 2 facedown cards in your provinces – turn the chosen cards faceup.','holding','false');");
        }
        
        public override void Down()
        {
        }
    }
}
