namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingCraneAndDragonConflict : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',1,3,NULL,0,0,0,'steward-of-law','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_139.jpg',1,0,'false','false',1,NULL,'Steward of Law',1,NULL,NULL,'conflict',0,NULL,'While this character is participating in a conflict, characters cannot become dishonored.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',3,3,NULL,0,0,0,'political-rival','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_140.jpg',2,0,'false','false',0,NULL,'Political Rival',3,NULL,NULL,'conflict',0,NULL,'Covert. <i>(When this character attacks, choose one character without covert. That character cannot be declared as a defender.)</i> This character gets +3[conflict-political] while defending.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',1,3,NULL,0,0,0,'above-question','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_141.jpg',2,0,'false','false',0,'+0','Above Question',0,+0,NULL,'conflict',0,NULL,'Attached character cannot be chosen as a target of an opponent''s event.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',1,3,NULL,0,0,0,'duelist-training','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_142.jpg',1,0,'false','false',0,'+0','Duelist Training',0,+0,NULL,'conflict',0,NULL,'Attached character gains: <b>Action:</b> While this character is participating in a conflict, choose a participating character controlled by your opponent – challenge that character to a [conflict-military] duel. Instead of giving honor for this duel''s bid, a player may choose and discard the required number of cards from hand. Bow the loser of the duel.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',2,3,NULL,0,0,0,'height-of-fashion','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_143.jpg',3,0,'false','false',0,'+0','Height of Fashion',0,+4,NULL,'conflict',0,NULL,'This attachment cannot be played during a conflict.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',0,3,NULL,0,0,0,'the-perfect-gift','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_144.jpg',1,0,'false','false',0,NULL,'The Perfect Gift',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Reveal the top 4 cards of each player''s conflict deck. Choose 1 revealed card owned by each player and add it to its owner''s hand. Shuffle.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',0,3,NULL,0,0,0,'voice-of-honor','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_145.jpg',2,0,'false','false',0,NULL,'Voice of Honor',0,NULL,NULL,'conflict',0,NULL,'<b>Interrupt:</b> When the effects of an event would initiate, if you control more honored characters than an opponent – cancel those effects.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',0,3,NULL,0,0,0,'way-of-the-crane','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_146.jpg',0,0,'false','false',0,NULL,'Way of the Crane',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Choose a [clan-crane] character you control – honor that character.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',1,3,NULL,0,0,0,'admit-defeat','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_147.jpg',2,0,'false','false',0,NULL,'Admit Defeat',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Choose a character that is defending alone – bow that character.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crane',1,3,NULL,0,0,0,'noble-sacrifice','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_148.jpg',2,0,'false','false',0,NULL,'Noble Sacrifice',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Sacrifice a <i>(friendly)</i> honored character. Choose a dishonored character – discard that character.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',1,3,NULL,0,0,0,'tattooed-wanderer','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_149.jpg',2,0,'false','false',2,NULL,'Tattooed Wanderer',1,NULL,NULL,'conflict',0,NULL,'You may play this character as an attachment with the text: Attached character gains covert. ','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',3,3,NULL,0,1,0,'togashi-kazue','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_150.jpg',2,0,'false','false',3,NULL,'Togashi Kazue',3,NULL,NULL,'conflict',0,NULL,'You may play this character as an attachment with the text: <b>Action:</b> During a conflict in which attached character is participating, choose another participating character – move 1 fate from that character to the attached character.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',1,3,NULL,0,0,0,'ancestral-daisho','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_151.jpg',2,0,'false','false',0,'+2','Ancestral Daishō',0,+0,NULL,'conflict',0,NULL,'Ancestral. <i>(When attached card leaves play, return this card to your hand.)</i> Restricted. <i>(No more than two restricted attachments per character.)</i>','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',0,3,NULL,0,0,0,'daimyo-s-favor','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_152.jpg',2,0,'false','false',0,'+0','Daimyō''s Favor',0,+0,NULL,'conflict',0,NULL,'Attach to a character you control. <b>Action:</b> Bow this attachment – reduce the cost of the next attachment you play on this character this phase by 1.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',1,3,NULL,0,0,0,'kitsuki-s-method','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_153.jpg',2,0,'false','false',0,'+0','Kitsuki''s Method',0,+2,NULL,'conflict',0,NULL,'Ancestral. <i>(When attached card leaves play, return this card to your hand.)</i> Restricted. <i>(No more than two restricted attachments per character.)</i>','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',2,3,NULL,0,0,0,'way-of-the-dragon','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_154.jpg',0,0,'false','false',0,'+1','Way of the Dragon',0,+1,NULL,'conflict',0,NULL,'Attach to a character you control. Limit 1 per character. You may trigger each of attached character''s triggered abilities an additional time each round (or specified period).','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',0,3,NULL,0,0,0,'let-go','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_155.jpg',2,0,'false','false',0,NULL,'Let Go',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Choose an attachment – discard it.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',0,3,NULL,0,0,0,'mantra-of-fire','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_156.jpg',2,0,'false','false',0,NULL,'Mantra of Fire',0,NULL,NULL,'conflict',0,NULL,'<b>Reaction:</b> After an opponent declares a [element-fire] conflict, choose a <em>Monk</em> character or a character with a <em>Monk</em> attachment – place 1 fate on that character and draw 1 card.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',0,3,NULL,0,0,0,'tranquility','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_157.jpg',2,0,'false','false',0,NULL,'Tranquility',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict – until the end of the conflict, characters in your opponent''s home cannot trigger abilities.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',1,3,NULL,0,0,0,'indomitable-will','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_158.jpg',2,0,'false','false',0,NULL,'Indomitable Will',0,NULL,NULL,'conflict',0,NULL,'<b>Reaction:</b> After you win a conflict in which you control only a single participating character – that character does not bow as a result of the conflict''s resolution.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',1,3,NULL,0,0,0,'mirumoto-s-fury','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_159.jpg',2,0,'false','true',0,NULL,'Mirumoto''s Fury',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, choose an attacking character with glory X or lower – bow that character. X is equal to the number of unrevealed provinces you control.','event','false');");
        }
        
        public override void Down()
        {
        }
    }
}
