namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingCoreDragonDynasty : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',1,3,NULL,0,0,0,'doomed-shugenja','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_54.jpg',0,0,'false','false',3,NULL,'Doomed Shugenja',3,NULL,NULL,'dynasty',0,NULL,'Limited. <i>(No more than one limited card can be played by each player each round.)</i> You cannot place fate on this character when it is played from one of your provinces.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',1,3,NULL,0,2,0,'togashi-initiate','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_55.jpg',0,0,'false','false',1,NULL,'Togashi Initiate',1,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is attacking, spend 1 fate to an unclaimed ring – honor this character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',2,3,NULL,0,1,0,'agasha-swordsmith','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_56.jpg',0,0,'false','false',1,NULL,'Agasha Swordsmith',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> Search the top 5 cards of your conflict deck for an attachment, reveal it, and add it to your hand. Shuffle.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',2,3,NULL,0,1,0,'mirumoto-prodigy','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_57.jpg',0,0,'false','false',2,NULL,'Mirumoto Prodigy',2,NULL,NULL,'dynasty',0,NULL,'While this character is attacking alone, your opponent cannot declare more than one defender.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',2,3,NULL,0,1,0,'niten-adept','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_58.jpg',0,0,'false','false',2,NULL,'Niten Adept',1,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is participating in a conflict, bow a <i>(friendly)</i> attachment on it. Choose a participating character without attachments – bow that character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',2,3,NULL,0,0,0,'seeker-of-enlightenment','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_59.jpg',0,0,'false','false',1,NULL,'Seeker of Enlightenment',1,NULL,NULL,'dynasty',0,NULL,'This character gets +1[conflict-military] and +1[conflict-political] for each fate on each unclaimed ring.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',3,3,NULL,0,1,0,'enlightened-warrior','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_60.jpg',0,0,'false','false',2,NULL,'Enlightened Warrior',2,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After an opponent selects a ring with fate on it – place 1 fate on this character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',3,3,NULL,0,2,0,'kitsuki-investigator','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_61.jpg',0,0,'false','false',1,NULL,'Kitsuki Investigator',3,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is participating in a [conflict-political] conflict, spend 1 fate to an unclaimed ring – look at your opponent''s hand. Choose 1 of those cards and discard it. (Max 1 per conflict.)','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',3,3,NULL,0,1,0,'mirumoto-raitsugu','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_62.jpg',0,0,'false','false',3,NULL,'Mirumoto Raitsugu',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is participating in a conflict, choose a participating character controlled by your opponent – challenge that character to a [conflict-military] duel. If the loser of the duel has no fate on it, discard it. Otherwise remove 1 fate from it.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',4,3,NULL,0,1,0,'ascetic-visionary','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_63.jpg',0,0,'false','false',3,NULL,'Ascetic Visionary',4,NULL,NULL,'dynasty',0,NULL,'No attachments except <em>Monk</em> or <em>Tattoo</em>. <b>Action:</b> While this character is attacking, spend 1 fate to an unclaimed ring. Choose a <em>Monk</em> character or a character with a <em>Monk</em> attachment – ready that character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',4,3,NULL,0,2,0,'niten-master','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_64.jpg',0,0,'false','true',3,NULL,'Niten Master',3,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After you attach a <em>Weapon</em> attachment to this character – ready this character. (Limit twice per round.)','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',5,3,NULL,0,3,0,'togashi-yokuni','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_65.jpg',0,0,'false','false',5,NULL,'Togashi Yokuni',5,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> Choose a triggered ability printed on another character – this character gains that ability until the end of the phase. (Max 1 per round.)','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('dragon',0,3,NULL,0,0,0,'secluded-temple','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_66.jpg',0,0,'false','false',0,NULL,'Secluded Temple',0,NULL,NULL,'dynasty',0,+1,'<b>Reaction:</b> After the conflict phase begins, each opponent who controls more characters than you must choose a character he or she controls with 1 or more fate on it – remove 1 fate from each chosen character.','holding','false');");
        }
        
        public override void Down()
        {
        }
    }
}
