namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingCoreScorpionDynasty : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',1,3,NULL,0,0,0,'bayushi-liar','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_95.jpg',0,0,'false','false',0,NULL,'Bayushi Liar',3,NULL,NULL,'dynasty',0,NULL,'Sincerity. <i>(When this character leaves play, draw 1 card.)</i>','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',1,3,NULL,0,1,0,'bayushi-manipulator','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_96.jpg',0,0,'false','false',1,NULL,'Bayushi Manipulator',1,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After honor dials are revealed – increase the value of your bid by 1.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',1,3,NULL,0,0,0,'sinister-soshi','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_97.jpg',0,0,'false','false',0,NULL,'Sinister Soshi',0,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> During a conflict, choose a participating character – that character gets –2[conflict-military] and –2[conflict-political] until the end of the conflict.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',2,3,NULL,0,1,0,'blackmail-artist','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_98.jpg',0,0,'false','false',1,NULL,'Blackmail Artist',2,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After this character wins a [conflict-political] conflict – take 1 honor from your opponent.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',2,3,NULL,0,1,0,'soshi-illusionist','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_99.jpg',0,0,'false','false',1,NULL,'Soshi Illusionist',3,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> Spend 1 fate, choose a character – discard a status token from that character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',2,3,NULL,0,1,0,'yogo-outcast','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_100.jpg',0,0,'false','false',2,NULL,'Yogo Outcast',2,NULL,NULL,'dynasty',0,NULL,'This character gets +1[conflict-military] and +1[conflict-political] while you are less honorable than an opponent.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',2,3,NULL,0,1,0,'young-rumormonger','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_101.jpg',0,0,'false','false',2,NULL,'Young Rumormonger',2,NULL,NULL,'dynasty',0,NULL,'<b>Interrupt:</b> When a character would be honored or dishonored, choose another character controlled by the same player – that character receives the honor or dishonor instead.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',3,3,NULL,0,2,0,'favored-niece','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_102.jpg',0,0,'false','false',2,NULL,'Favored Niece',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> Choose and discard 1 card from your hand – draw 1 card. (Limit twice per round.)','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',3,3,NULL,0,1,0,'shosuro-actress','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_103.jpg',0,0,'false','false',1,NULL,'Shosuro Actress',3,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> During a conflict, sacrifice this character. Choose a non-<em>Shinobi</em> character with printed cost 3 or lower in an opponent''s discard pile – put that character into play in the conflict under your control.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',3,3,NULL,0,1,0,'shosuro-miyako','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_104.jpg',0,0,'false','false',3,NULL,'Shosuro Miyako',2,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After you play a character from your hand, your opponent must select one – discard 1 card at random from his or her hand or choose and dishonor a character he or she controls.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',4,3,NULL,0,2,0,'bayushi-yunako','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_105.jpg',0,0,'false','false',4,NULL,'Bayushi Yunako',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is participating in a conflict, choose a character – switch that character''s base [conflict-military] and [conflict-political] skill until the end of the conflict.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',4,3,NULL,0,2,0,'yogo-hiroue','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_106.jpg',0,0,'false','false',0,NULL,'Yogo Hiroue',4,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is participating in a conflict, choose a non-participating character – move that character to this conflict. Then, if you win the conflict, you may dishonor that character.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',5,3,NULL,0,2,0,'bayushi-shoju','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_107.jpg',0,0,'false','false',3,NULL,'Bayushi Shoju',7,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is participating in a [conflict-political] conflict, choose a participating character controlled by your opponent – until the end of the conflict, that character gets –1[conflict-political] and is discarded if its [conflict-political] skill is 0. (Limit twice per round.)','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',0,3,NULL,0,0,0,'city-of-lies','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_108.jpg',0,0,'false','false',0,NULL,'City of Lies',0,NULL,NULL,'dynasty',0,+1,'<b>Action:</b> Reduce the cost of the next event you play this phase by 1.','holding','false');");
        }
        
        public override void Down()
        {
        }
    }
}
