namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingCoreUnicornDynasty : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',1,3,NULL,0,1,0,'moto-youth','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_109.jpg',0,0,'false','false',2,NULL,'Moto Youth',0,NULL,NULL,'dynasty',0,NULL,'This character gets +1[conflict-military] during the first [conflict-military] conflict each round.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',1,3,NULL,0,1,0,'utaku-infantry','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_110.jpg',0,0,'false','false',0,NULL,'Utaku Infantry',0,NULL,NULL,'dynasty',0,NULL,'While this character is participating in a conflict, it gets +1[conflict-military] and +1[conflict-political] for each participating [clan-unicorn] character you control.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',2,3,NULL,0,0,0,'aggressive-moto','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_111.jpg',0,0,'false','false',3,NULL,'Aggressive Moto',0,NULL,NULL,'dynasty',0,NULL,'This character cannot be declared as a defender.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',2,3,NULL,0,1,0,'border-rider','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_112.jpg',0,0,'false','false',2,NULL,'Border Rider',1,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> Ready this character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',2,3,NULL,0,1,0,'meishodo-wielder','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_113.jpg',0,0,'false','false',2,NULL,'Meishōdō Wielder',2,NULL,NULL,'dynasty',0,NULL,'Reduce the cost to play this character by 1 while you are the first player.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',2,3,NULL,0,2,0,'shinjo-outrider','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_114.jpg',0,0,'false','false',2,NULL,'Shinjo Outrider',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> During a conflict – move this character to the conflict.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',3,3,NULL,0,2,0,'giver-of-gifts','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_115.jpg',0,0,'false','false',2,NULL,'Giver of Gifts',3,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> Choose an attachment you control – move that attachment to an eligible character you control.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',3,3,NULL,0,1,0,'ide-trader','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_116.jpg',0,0,'false','false',1,NULL,'Ide Trader',3,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After 1 or more characters move to a conflict in which this character is participating, select one – gain 1 fate or draw 1 card. (Limit once per conflict.)','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',3,3,NULL,0,2,0,'warrior-poet','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_117.jpg',0,0,'false','false',2,NULL,'Warrior Poet',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> While this character is participating in a conflict – each participating character controlled by your opponent gets –1[conflict-military] and –1[conflict-political] until the end of the conflict.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',3,3,NULL,0,3,0,'utaku-yumino','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_118.jpg',0,0,'false','false',2,NULL,'Utaku Yumino',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> During a conflict, discard a card from your hand – this character gets +2[conflict-military] and +2[conflict-political] until the end of the conflict. (Limit once per conflict.)','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',4,3,NULL,0,1,0,'moto-horde','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_119.jpg',0,0,'false','false',6,NULL,'Moto Horde',0,NULL,NULL,'dynasty',0,NULL,'No attachments except <em>Weapon</em>.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',4,3,NULL,0,2,0,'shinjo-tatsuo','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_119.jpg',0,0,'false','false',3,NULL,'Shinjo Tatsuo',3,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> During a conflict, choose this character and up to 1 other character you control – move those characters to the conflict.','character','true');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',5,3,NULL,0,2,0,'shinjo-altansarnai','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_121.jpg',0,0,'false','false',5,NULL,'Shinjo Altansarnai',4,NULL,NULL,'dynasty',0,NULL,'<b>Reaction:</b> After you break a province during a [conflict-military] conflict in which this character is participating, your opponent chooses a character he or she controls – discard that character.','character','true');");
        }
        
        public override void Down()
        {
        }
    }
}
