// <auto-generated />
namespace L5R_DBH_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PopulatingCorePhoenixDynasty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulatingCorePhoenixDynasty));
        
        string IMigrationMetadata.Id
        {
            get { return "202002271855243_PopulatingCorePhoenixDynasty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
