namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingScorpionAndUnicornConflict : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',2,3,NULL,0,0,0,'adept-of-shadows','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_180.jpg',3,0,'false','false',2,NULL,'Adept of Shadows',2,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Lose 1 honor – return this character to your hand.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',3,3,NULL,0,0,0,'unassuming-yojimbo','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_181.jpg',2,0,'false','false',3,NULL,'Unassuming Yōjimbō',1,NULL,NULL,'conflict',0,NULL,'Covert. <i>(When this character attacks, choose one character without covert. That character cannot be declared as a defender.)</i>','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',1,3,NULL,0,0,0,'court-mask','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_182.jpg',1,0,'false','false',0,'+1','Court Mask',0,+2,NULL,'conflict',0,NULL,'Attach to a character you control. <b>Action:</b> Return this attachment to your hand and dishonor attached character.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',1,3,NULL,0,0,0,'fiery-madness','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_183.jpg',2,0,'false','false',0,'-2','Fiery Madness',0,-2,NULL,'conflict',0,NULL,NULL,'attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',0,3,NULL,0,0,0,'forged-edict','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_184.jpg',2,0,'false','true',0,NULL,'Forged Edict',0,NULL,NULL,'conflict',0,NULL,'<b>Interrupt:</b> When the effects of an event would initiate, dishonor a <i>(friendly)</i> <em>Courtier</em> character – cancel those effects.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',0,3,NULL,0,0,0,'way-of-the-scorpion','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_185.jpg',0,0,'false','false',0,NULL,'Way of the Scorpion',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, choose a participating non-[clan-scorpion] character – dishonor that character.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',1,3,NULL,0,0,0,'calling-in-favors','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_186.jpg',2,0,'false','false',0,NULL,'Calling in Favors',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Dishonor a <i>(friendly)</i> character. Choose an opponent''s attachment – take control of that attachment and attach it to that character, if able. Otherwise, discard the attachment.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',2,3,NULL,0,0,0,'i-can-swim','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_187.jpg',1,0,'false','false',0,NULL,'I Can Swim',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, if the bid on your honor dial is higher than an opponent''s, choose a participating dishonored character controlled by that opponent – discard that character.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',3,3,NULL,0,0,0,'ambush','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_188.jpg',1,0,'false','false',0,NULL,'Ambush',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, choose up to 2 [clan-scorpion] characters with total printed cost 6 or lower from your hand and/or provinces – put those characters into play as participating characters.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('scorpion',3,3,NULL,0,0,0,'blackmail','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_189.jpg',3,0,'false','false',0,NULL,'Blackmail',0,NULL,NULL,'conflict',0,NULL,'Play only if you are less honorable than your opponent. <b>Action:</b> During a conflict, choose a character with printed cost 2 or lower controlled by your opponent – take control of that character until the end of the conflict.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',1,3,NULL,0,0,0,'iuchi-wayfinder','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_190.jpg',1,0,'false','false',1,NULL,'Iuchi Wayfinder',1,NULL,NULL,'conflict',0,NULL,'<b>Reaction:</b> After this character enters play – look at a facedown province.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',2,3,NULL,0,0,0,'ide-messenger','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_191.jpg',1,0,'false','false',1,NULL,'Ide Messenger',2,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, spend 1 fate. Choose a character you control – move that character to the conflict.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',1,3,NULL,0,0,0,'favored-mount','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_192.jpg',1,0,'false','false',0,'+1','Favored Mount',0,+0,NULL,'conflict',0,NULL,'Attach to a character you control. Attached character gains <em>Cavalry</em>. <b>Action:</b> During a conflict, bow this attachment – move attached character to the conflict.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',1,3,NULL,0,0,0,'spyglass','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_193.jpg',2,0,'false','true',0,'+0','Spyglass',0,+1,NULL,'conflict',0,NULL,'<b>Reaction:</b> After attached character commits to a conflict or moves to a conflict – draw 1 card. (Limit twice per round.)','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',2,3,NULL,0,0,0,'born-in-war','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_194.jpg',1,0,'false','false',0,'+X','Born in War',0,+0,NULL,'conflict',0,NULL,'<em>Cavalry</em> character only. X is equal to the number of unclaimed rings.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',0,3,NULL,0,0,0,'breakthrough','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_195.jpg',1,0,'false','false',0,NULL,'Breakthrough',0,NULL,NULL,'conflict',0,NULL,'<b>Reaction:</b> After the resolution of your first conflict this phase as the attacking player, if that conflict broke a province – immediately declare your second conflict for this phase.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',0,3,NULL,0,0,0,'captive-audience','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_196.jpg',3,0,'false','false',0,NULL,'Captive Audience',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a [conflict-political] conflict, lose 1 honor – change the conflict cardType to [conflict-military].','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',0,3,NULL,0,0,0,'i-am-ready','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_197.jpg',1,0,'false','false',0,NULL,'I Am Ready',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Remove 1 fate from a <i>(friendly)</i> [clan-unicorn] character – ready that character.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',0,3,NULL,0,0,0,'way-of-the-unicorn','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_198.jpg',0,0,'false','false',0,NULL,'Way of the Unicorn',0,NULL,NULL,'conflict',0,NULL,'<b>Interrupt:</b> When you would pass the first player token – keep it instead.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('unicorn',3,3,NULL,0,0,0,'cavalry-reserves','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_199.jpg',2,0,'false','false',0,NULL,'Cavalry Reserves',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a [conflict-military] conflict, choose up to 6 printed cost worth of <em>Cavalry</em> characters in your dynasty discard pile – put those characters into play in the conflict.','event','false');");
        }
        
        public override void Down()
        {
        }
    }
}
