namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingCoreCards : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('crab', 0, 1, NULL, 7, 0, 10, 'shiro-nishiyama', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_1.jpg', 0, 10, 'false', 'false', 0, NULL, 'Shiro Nishiyama', 0, NULL, NULL, 'province', 0, +3, '<b>Action:</b> During a conflict, bow this stronghold – each defending character you control gets +1[conflict-military] and +1[conflict-political] until the end of the conflict.', 'stronghold', 'true'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('crane', 0, 1, NULL, 7, 0, 11, 'shizuka-toshi', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_2.jpg', 0, 10, 'false', 'false', 0, NULL, 'Shizuka Toshi', 0, NULL, NULL, 'province', 0, +2, '<b>Action:</b> During a [conflict-political] conflict, bow this stronghold. Choose a participating character with [conflict-political] skill 2 or lower – bow that character.', 'stronghold', 'true'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('dragon', 0, 1, NULL, 7, 0, 11, 'mountain-s-anvil-castle', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_3.jpg', 0, 10, 'false', 'false', 0, NULL, 'Mountain''s Anvil Castle', 0, NULL, NULL, 'province', 0, +2, '<b>Action:</b> During a conflict, bow this stronghold. Choose a participating character with 1 or more attachments on it – until the end of the conflict, that character gets +1[conflict-military] and +1[conflict-political] (+2[conflict-military] and +2[conflict-political] instead if it has 2 or more attachments on it).', 'stronghold', 'true'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('lion', 0, 1, NULL, 7, 0, 12, 'yojin-no-shiro', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_4.jpg', 0, 10, 'false', 'false', 0, NULL, 'Yōjin no Shiro', 0, NULL, NULL, 'province', 0, +2, '<b>Action:</b> During a conflict, bow this stronghold – each attacking character you control gets +1[conflict-military] until the end of the conflict.', 'stronghold', 'true'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('phoenix', 0, 1, NULL, 7, 0, 11, 'isawa-mori-seido', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_5.jpg', 0, 10, 'false', 'false', 0, NULL, 'Isawa Mori Seidō', 0, NULL, NULL, 'province', 0, +2, '<b>Action:</b> Bow this stronghold, choose a character – that character gets +2 glory until the end of the phase.', 'stronghold', 'true'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('scorpion', 0, 1, NULL, 7, 0, 10, 'city-of-the-open-hand', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_6.jpg', 0, 10, 'false', 'false', 0, NULL, 'City of the Open Hand', 0, NULL, NULL, 'province', 0, +1, '<b>Action:</b> If you are less honorable than an opponent, bow this stronghold and select one – either that opponent loses 1 honor, or you gain 1 honor. <i>Errata from RRG v9</i>', 'stronghold', 'true'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('unicorn', 0, 1, NULL, 7, 0, 10, 'golden-plains-outpost', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_7.jpg', 0, 10, 'false', 'false', 0, NULL, 'Golden Plains Outpost', 0, NULL, NULL, 'province', 0, +0, '<b>Action:</b> During a [conflict-military] conflict, bow this stronghold. Choose a <em>Cavalry</em> character you control – move it to that conflict.', 'stronghold', 'true'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('crab', 0, 1, 'earth', 0, 0, 0, 'defend-the-wall', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_8.jpg', 0, 0, 'false', 'false', 0, NULL, 'Defend the Wall', 0, NULL, NULL, 'province', 4, NULL, '<b>Reaction:</b> After you win a conflict at this province – resolve the ring effect of that conflict as if you were the attacking player.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('crane', 0, 1, 'air', 0, 0, 0, 'the-art-of-peace', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_9.jpg', 0, 0, 'false', 'false', 0, NULL, 'The Art of Peace', 0, NULL, NULL, 'province', 4, NULL, '<b>Interrupt:</b> When this province is broken – dishonor each attacking character and honor each defending character.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('dragon', 0, 1, 'fire', 0, 0, 0, 'restoration-of-balance', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_10.jpg', 0, 0, 'false', 'false', 0, NULL, 'Restoration of Balance', 0, NULL, NULL, 'province', 3, NULL, '<b>Interrupt:</b> When this province is broken – your opponent chooses and discards cards from his or her hand until that player has 4 or fewer cards in hand. <i>Errata from RRG v9</i>', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('lion', 0, 1, 'water', 0, 0, 0, 'the-art-of-war', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_11.jpg', 0, 0, 'false', 'false', 0, NULL, 'The Art of War', 0, NULL, NULL, 'province', 3, NULL, '<b>Interrupt:</b> When this province is broken – draw 3 cards.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('phoenix', 0, 1, 'void', 0, 0, 0, 'kuroi-mori', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_12.jpg', 0, 0, 'false', 'false', 0, NULL, 'Kuroi Mori', 0, NULL, NULL, 'province', 4, NULL, '<b>Action:</b> During a conflict at this province, select one – switch the contested ring with an unclaimed ring <i>(the conflict retains its cardType)</i>, or switch the conflict cardType <i>(the conflict retains its element)</i>.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('scorpion', 0, 1, 'air', 0, 0, 0, 'secret-cache', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_13.jpg', 0, 0, 'false', 'true', 0, NULL, 'Secret Cache', 0, NULL, NULL, 'province', 4, NULL, '<b>Reaction:</b> After a conflict is declared against this province – search the top 5 cards of your conflict deck for a card and add it to your hand. Shuffle.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('unicorn', 0, 1, 'water', 0, 0, 0, 'endless-plains', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_14.jpg', 0, 0, 'false', 'false', 0, NULL, 'Endless Plains', 0, NULL, NULL, 'province', 2, NULL, '<b>Reaction:</b> After an attack is declared here, break this province. Your opponent chooses an attacking character – discard that character.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'earth', 0, 0, 0, 'ancestral-lands', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_15.jpg', 0, 0, 'false', 'false', 0, NULL, 'Ancestral Lands', 0, NULL, NULL, 'province', 5, NULL, 'This province gets +5 strength during [conflict-political] conflicts.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'water', 0, 0, 0, 'elemental-fury', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_16.jpg', 0, 0, 'false', 'false', 0, NULL, 'Elemental Fury', 0, NULL, NULL, 'province', 4, NULL, '<b>Reaction:</b> After this province is revealed – switch the contested ring with an unclaimed ring. <i>(The conflict retains its cardType.)</i>', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'earth', 0, 0, 0, 'entrenched-position', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_17.jpg', 0, 0, 'false', 'false', 0, NULL, 'Entrenched Position', 0, NULL, NULL, 'province', 5, NULL, 'This province gets +5 strength during [conflict-military] conflicts.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'air', 0, 0, 0, 'fertile-fields', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_18.jpg', 0, 0, 'false', 'false', 0, NULL, 'Fertile Fields', 0, NULL, NULL, 'province', 4, NULL, '<b>Action:</b> During a conflict at this province – draw 1 card.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'air', 0, 0, 0, 'manicured-garden', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_19.jpg', 0, 0, 'false', 'false', 0, NULL, 'Manicured Garden', 0, NULL, NULL, 'province', 4, NULL, '<b>Action:</b> During a conflict at this province – gain 1 fate.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'fire', 0, 0, 0, 'meditations-on-the-tao', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_20.jpg', 0, 0, 'false', 'false', 0, NULL, 'Meditations on the Tao', 0, NULL, NULL, 'province', 4, NULL, '<b>Action:</b> During a conflict at this province, choose an attacking character – remove 1 fate from that character.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'fire', 0, 0, 0, 'night-raid', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_21.jpg', 0, 0, 'false', 'false', 0, NULL, 'Night Raid', 0, NULL, NULL, 'province', 4, NULL, '<b>Reaction:</b> After this province is revealed – your opponent chooses and discards X cards from his or her hand. X is equal to the number of attacking characters.', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'void', 0, 0, 0, 'pilgrimage', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_22.jpg', 0, 0, 'false', 'false', 0, NULL, 'Pilgrimage', 0, NULL, NULL, 'province', 5, NULL, 'During conflicts at this province, cancel all ring effects. <i>(If this province breaks, resolve ring effects as normal.)</i>', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'water', 0, 0, 0, 'rally-to-the-cause', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_23.jpg', 0, 0, 'false', 'false', 0, NULL, 'Rally to the Cause', 0, NULL, NULL, 'province', 4, NULL, '<b>Reaction:</b> After this province is revealed – switch the conflict cardType. <i>(The conflict retains its element.)</i>', 'province', 'false'); ");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES('neutral', 0, 1, 'void', 0, 0, 0, 'shameful-display', 'http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_24.jpg', 0, 0, 'false', 'false', 0, NULL, 'Shameful Display', 0, NULL, NULL, 'province', 3, NULL, '<b>Action:</b> During a conflict at this province, choose 2 participating characters – honor one of those characters and dishonor the other.', 'province', 'false'); ");
            

        }

        public override void Down()
        {
        }
    }
}
