namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingNeutralDynastyAndConflictCrabCore : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',1,3,NULL,0,1,0,'otomo-courtier','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_122.jpg',0,0,'false','false',0,NULL,'Otomo Courtier',2,NULL,NULL,'dynasty',0,NULL,'This character cannot participate in conflicts as an attacker against a player that controls the Imperial Favor.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',1,3,NULL,0,1,0,'seppun-guardsman','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_123.jpg',0,0,'false','false',2,NULL,'Seppun Guardsman',0,NULL,NULL,'dynasty',0,NULL,'This character cannot participate in conflicts as an attacker against a player that controls the Imperial Favor.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',2,3,NULL,0,2,0,'keeper-initiate','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_124.jpg',0,0,'false','false',1,NULL,'Keeper Initiate',1,NULL,'keeper','dynasty',0,NULL,'<em>Keeper</em> role only. <b>Reaction:</b> After you claim a ring that matches the element of your role – put this character into play from your dynasty discard pile or provinces. Then, put 1 fate on this character.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',2,3,NULL,0,1,0,'miya-mystic','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_125.jpg',0,0,'false','false',1,NULL,'Miya Mystic',1,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> During the conflict phase, sacrifice this character. Choose an attachment – discard that attachment.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',2,3,NULL,0,2,0,'seeker-initiate','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_126.jpg',0,0,'false','false',1,NULL,'Seeker Initiate',1,NULL,'seeker','dynasty',0,NULL,'<em>Seeker</em> role only. <b>Reaction:</b> After you claim a ring that matches the element of your role – search the top 5 cards of your conflict deck for a card and add it to your hand. Shuffle.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',3,3,NULL,0,0,0,'wandering-ronin','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_127.jpg',0,0,'false','false',2,NULL,'Wandering Ronin',2,NULL,NULL,'dynasty',0,NULL,'<b>Action:</b> During a conflict, remove 1 fate from this character – it gets +2[conflict-military] and +2[conflict-political] until the end of the conflict. (Limit twice per conflict.)','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'favorable-ground','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_128.jpg',0,0,'false','false',0,NULL,'Favorable Ground',0,NULL,NULL,'dynasty',0,+1,'<b>Action:</b> During a conflict, sacrifice this holding. Choose a character you control – move that character to the conflict or home from the conflict.','holding','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'imperial-storehouse','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_129.jpg',0,0,'false','false',0,NULL,'Imperial Storehouse',0,NULL,NULL,'dynasty',0,+1,'<b>Action:</b> Sacrifice this holding – draw 1 card.','holding','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',2,3,NULL,0,0,0,'hiruma-ambusher','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_130.jpg',1,0,'false','false',2,NULL,'Hiruma Ambusher',2,NULL,NULL,'conflict',0,NULL,'<b>Reaction:</b> After this character enters play as a defender, choose a character – that character''s abilities cannot be triggered during this conflict.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',2,3,NULL,0,1,0,'stoic-gunso','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_131.jpg',1,0,'false','false',2,NULL,'Stoic Gunsō',1,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, sacrifice a <i>(friendly)</i> character – this character gets +3[conflict-military] until the end of the conflict.','character','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',1,3,NULL,0,0,0,'reprieve','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_132.jpg',1,0,'false','false',0,'+0','Reprieve',0,+0,NULL,'conflict',0,NULL,'<b>Interrupt:</b> When attached character would leave play – discard this attachment instead.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',1,3,NULL,0,0,0,'watch-commander','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_133.jpg',3,0,'false','false',0,'+1','Watch Commander',0,+1,NULL,'conflict',0,NULL,'Attach to a character you control. Limit 1 per character. <b>Reaction:</b> After an opponent plays a card during a conflict in which attached character is participating – that player loses 1 honor. (Unlimited.)','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',2,3,NULL,0,0,0,'jade-tetsubo','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_134.jpg',2,0,'false','false',0,'+3','Jade Tetsubō',0,+0,NULL,'conflict',0,NULL,'Attach to a character you control. Restricted. <b>Action:</b> While attached character is participating in a conflict, bow this attachment. Choose a participating character with lower [conflict-military] skill than attached character – return all fate on that character to its owner''s fate pool.','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',0,3,NULL,0,0,0,'levy','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_135.jpg',3,0,'false','false',0,NULL,'Levy',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Choose an opponent, that player must select one – give you 1 fate or 1 honor.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',0,3,NULL,0,0,0,'rebuild','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_136.jpg',2,0,'false','true',0,NULL,'Rebuild',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Shuffle a card in one of your unbroken provinces back into your dynasty deck. Choose a holding in your dynasty discard pile – put that holding into play in that province.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',1,3,NULL,0,0,0,'way-of-the-crab','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_137.jpg',0,0,'false','false',0,NULL,'Way of the Crab',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Sacrifice a <i>(friendly)</i> [clan-crab] character. Choose an opponent – that player must sacrifice a character. (Max 1 per round.)','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('crab',1,3,NULL,0,0,0,'the-mountain-does-not-fall','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_138.jpg',3,0,'false','false',0,NULL,'The Mountain Does Not Fall',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> Choose a character – until the end of the phase, that character does not bow as a result of conflict resolution while defending. (Max 1 per round.)','event','false');");
        }
        
        public override void Down()
        {
        }
    }
}
