namespace L5R_DBH_MVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulatingNeutralConflictAndRoles : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'fine-katana','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_200.jpg',0,0,'false','false',0,'+2','Fine Katana',0,+0,NULL,'conflict',0,NULL,'Restricted. <i>(No more than two restricted attachments per character.)</i>','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'ornate-fan','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_201.jpg',0,0,'false','false',0,'+0','Ornate Fan',0,+2,NULL,'conflict',0,NULL,'Restricted. <i>(No more than two restricted attachments per character.)</i>','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',1,3,NULL,0,0,0,'cloud-the-mind','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_202.jpg',0,0,'false','false',0,'+0','Cloud the Mind',0,+0,NULL,'conflict',0,NULL,'Play only if you control a <em>Shugenja</em> character. Treat attached character as if its printed text box were blank (except for <em>Traits</em>).','attachment','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'assassination','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_203.jpg',0,0,'false','false',0,NULL,'Assassination',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, lose 3 honor. Choose a character with printed cost 2 or lower – discard that character. (Max 1 per round.)','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'banzai','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_204.jpg',0,0,'false','false',0,NULL,'Banzai!',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, choose a participating character – that character gets +2[conflict-military] until the end of the conflict. You may lose 1 honor to resolve this ability twice. (Max 1 per conflict.)','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'contingency-plan','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_205.jpg',0,0,'false','false',0,NULL,'Contingency Plan',0,NULL,NULL,'conflict',0,NULL,'<b>Reaction:</b> After honor dials are revealed – increase or decrease the value of your bid by 1 <i>(to a minimum of 0)</i>.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'court-games','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_206.jpg',0,0,'false','false',0,NULL,'Court Games',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a [conflict-political] conflict, select one – choose and honor a participating character you control, or your opponent chooses and dishonors a participating character he or she controls. (Max 1 per conflict.)','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'for-shame','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_207.jpg',0,0,'false','false',0,NULL,'For Shame!',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, if you control a participating <em>Courtier</em> character, choose a participating character controlled by your opponent. Your opponent must select one – dishonor the chosen character or bow it.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'good-omen','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_208.jpg',0,0,'false','false',0,NULL,'Good Omen',0,NULL,NULL,'conflict',0,NULL,'Play only if your honor bid is lower than an opponent''s. <b>Action:</b> Choose a character with printed cost 3 or higher – place 1 fate on that character.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,3,NULL,0,0,0,'spies-at-court','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_209.jpg',0,0,'false','false',0,NULL,'Spies at Court',0,NULL,NULL,'conflict',0,NULL,'<b>Reaction:</b> After you win a [conflict-political] conflict, dishonor a <i>(friendly)</i> participating character – discard 2 cards at random from your opponent''s hand. (Max 1 per conflict.)','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',1,3,NULL,0,0,0,'charge','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_210.jpg',0,0,'true','false',0,NULL,'Charge!',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a [conflict-military] conflict, choose a character in one of your provinces – put that character into play in the conflict.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',1,3,NULL,0,0,0,'fallen-in-battle','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_211.jpg',0,0,'false','false',0,NULL,'Fallen in Battle',0,NULL,NULL,'conflict',0,NULL,'<b>Reaction:</b> After you win a [conflict-military] conflict by 5 or more skill, choose a participating character – discard that character. (Max 1 per conflict.)','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',1,3,NULL,0,0,0,'outwit','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_212.jpg',0,0,'false','false',0,NULL,'Outwit',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, choose an opponent''s character with lower [conflict-political] skill than a participating <em>Courtier</em> character you control – move the chosen character home.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',1,3,NULL,0,0,0,'rout','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_213.jpg',0,0,'false','false',0,NULL,'Rout',0,NULL,NULL,'conflict',0,NULL,'<b>Action:</b> During a conflict, choose an opponent''s character with lower [conflict-military] skill than a participating <em>Bushi</em> character you control – move the chosen character home.','event','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'keeper-of-air','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_214A.jpg',0,0,'false','false',0,NULL,'Keeper of Air',0,NULL,NULL,'role',0,NULL,'Increase your deckbuilding influence value by 3. <b>Reaction:</b> After you win an [element-air] conflict as the defending player – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'seeker-of-air','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_214B.jpg',0,0,'false','false',0,NULL,'Seeker of Air',0,NULL,NULL,'role',0,NULL,'You may replace 1 province of any element with an additional [element-air] province while deckbuilding. <b>Reaction:</b> After an [element-air] province you control is revealed – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'keeper-of-earth','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_215A.jpg',0,0,'false','false',0,NULL,'Keeper of Earth',0,NULL,NULL,'role',0,NULL,'Increase your deckbuilding influence value by 3. <b>Reaction:</b> After you win an [element-earth] conflict as the defending player – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'seeker-of-earth','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_215B.jpg',0,0,'false','false',0,NULL,'Seeker of Earth',0,NULL,NULL,'role',0,NULL,'You may replace 1 province of any element with an additional [element-earth] province while deckbuilding. <b>Reaction:</b> After an [element-earth] province you control is revealed – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'keeper-of-fire','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_216A.jpg',0,0,'false','false',0,NULL,'Keeper of Fire',0,NULL,NULL,'role',0,NULL,'Increase your deckbuilding influence value by 3. <b>Reaction:</b> After you win a [element-fire] conflict as the defending player – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'seeker-of-fire','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_216B.jpg',0,0,'false','false',0,NULL,'Seeker of Fire',0,NULL,NULL,'role',0,NULL,'You may replace 1 province of any element with an additional [element-fire] province while deckbuilding. <b>Reaction:</b> After a [element-fire] province you control is revealed – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'keeper-of-water','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_217A.jpg',0,0,'false','false',0,NULL,'Keeper of Water',0,NULL,NULL,'role',0,NULL,'Increase your deckbuilding influence value by 3. <b>Reaction:</b> After you win a [element-water] conflict as the defending player – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'seeker-of-water','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_217B.jpg',0,0,'false','false',0,NULL,'Seeker of Water',0,NULL,NULL,'role',0,NULL,'You may replace 1 province of any element with an additional [element-water] province while deckbuilding. <b>Reaction:</b> After a [element-water] province you control is revealed – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'keeper-of-void','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_218A.jpg',0,0,'false','false',0,NULL,'Keeper of Void',0,NULL,NULL,'role',0,NULL,'Increase your deckbuilding influence value by 3. <b>Reaction:</b> After you win a [element-void] conflict as the defending player – gain 1 fate.','role','false');");
            Sql("INSERT INTO Cards(Clan, Cost, DeckLimit, Element, Fate, Glory, Honor, Id, ImageLocation, InfluenceCost, InfluencePool, IsBanned, IsRestricted, Military, MilitaryBonus, Name, Political, PoliticalBonus, RoleRestriction, Side, Strength, StrengthOf, Text, CardType, Unicity) VALUES ('neutral',0,1,NULL,0,0,0,'seeker-of-void','http://lcg-cdn.fantasyflightgames.com/l5r/L5C01_218B.jpg',0,0,'false','false',0,NULL,'Seeker of Void',0,NULL,NULL,'role',0,NULL,'You may replace 1 province of any element with an additional [element-void] province while deckbuilding. <b>Reaction:</b> After a [element-void] province you control is revealed – gain 1 fate.','role','false');");
        }
        
        public override void Down()
        {
        }
    }
}
